---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://gitlab.com/philipz/code-with-quarkus.git
    app.quarkus.io/build-timestamp: 2021-01-15 - 15:14:49 +0000
    app.quarkus.io/commit-id: 4ff799db7da56dcef3502e41e97ab0d4e4723802
  labels:
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: code-with-quarkus
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: debug
    port: 5005
    targetPort: 5005
  selector:
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://gitlab.com/philipz/code-with-quarkus.git
    app.quarkus.io/build-timestamp: 2021-01-15 - 15:14:49 +0000
    app.quarkus.io/commit-id: 4ff799db7da56dcef3502e41e97ab0d4e4723802
  labels:
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: code-with-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: code-with-quarkus
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://gitlab.com/philipz/code-with-quarkus.git
        app.quarkus.io/build-timestamp: 2021-01-15 - 15:14:49 +0000
        app.quarkus.io/commit-id: 4ff799db7da56dcef3502e41e97ab0d4e4723802
      labels:
        app.kubernetes.io/name: code-with-quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: philipz/code-with-quarkus:debug
        imagePullPolicy: Always
        name: code-with-quarkus
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 5005
          name: debug
          protocol: TCP